# Generated by Django 6.1.1 on 2026-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('food_cost_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('upi_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
