# Generated by Django 6.1.1 on 2026-09-05 17:54

import django.db.models.deletion
import tables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. Table 01, T-12', max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('shape', models.CharField(choices=[('SQUARE', 'Square (4-Seats)'), ('ROUND', 'Round (2-Seats)'), ('RECTANGLE', 'Rectangle (6+ Seats)')], default='SQUARE', max_length=20)),
                ('floor_section', models.CharField(default='Indoor Main Floor', max_length=50)),
                ('public_token', models.CharField(default=tables.models.generate_token, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('ORDERING', 'Customer Ordering'), ('PREPARING', 'Food Preparing'), ('SERVED', 'Food Served'), ('BILL_REQUESTED', 'Bill Requested'), ('CLEANING', 'Cleaning')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=32, unique=True)),
                ('guest_count', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Session'), ('BILL_REQUESTED', 'Bill Requested'), ('PAID', 'Paid'), ('CLOSED', 'Session Closed')], default='ACTIVE', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_sessions', to='customers.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
