# Generated by Django 6.1.1 on 2026-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='waiter_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='waiter_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
