# Generated by Django 6.1.1 on 2026-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_tablesession_is_bill_issued_tablereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Duration in minutes (e.g. 60, 90, 120, 180)'),
        ),
    ]
