# Generated by Django 6.1.1 on 2026-09-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_tablereservation_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='booking_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='client_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='manager_15m_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
