# Generated by Django 6.1.1 on 2026-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('INVOICE', 'Invoice PDF Dispatch'), ('FEEDBACK_REQUEST', 'Feedback Survey Request'), ('ORDER_CONFIRMATION', 'Order Status Alert')], max_length=30)),
                ('template_name', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(default=dict)),
                ('preview_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered to WhatsApp'), ('READ', 'Read by Customer'), ('FAILED', 'Failed Delivery')], default='DELIVERED', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
