# Generated by Django 6.1.1 on 2026-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_reason', models.CharField(blank=True, max_length=150)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid (Split Payment)'), ('PAID', 'Fully Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI (GPay, PhonePe, Paytm)'), ('CARD', 'Credit / Debit Card'), ('OTHER', 'Other / Digital Wallet')], default='UPI', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(blank=True, help_text='Transaction or UTR number', max_length=100)),
                ('payer_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful'), ('PENDING', 'Processing'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('processed_by', models.CharField(default='Cashier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
