# Generated by Django 6.1.1 on 2026-09-07 18:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage Discount'), ('FLAT', 'Flat Amount Discount')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('500.00'), max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bill',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_name', models.CharField(default='Cashier', max_length=100)),
                ('shift_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Active Shift'), ('CLOSED', 'Closed & Reconciled')], default='OPEN', max_length=20)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Starting cash in drawer', max_digits=10)),
                ('closing_cash_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Counted drawer cash by cashier', max_digits=10)),
                ('closing_cash_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive = Excess, Negative = Shortage', max_digits=10)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_upi_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_other_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tips', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bills_count', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cashier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.CharField(help_text='e.g. Emergency mint leaves, Ice bag, cleaning supplies', max_length=200)),
                ('approved_by', models.CharField(default='Manager', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='billing.cashiershift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
