# Generated by Django 6.1.1 on 2026-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cafeprofile_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeprofile',
            name='advance_booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='waiter_call_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
