# Generated by Django 6.1.1 on 2026-09-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('order_source', models.CharField(choices=[('QR', 'Customer QR Scan'), ('WAITER_MANUAL', 'Staff / Waiter POS')], default='QR', max_length=20)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('CONFIRMED', 'Confirmed by Staff'), ('PREPARING', 'Preparing in Kitchen'), ('READY', 'Ready for Pickup / Serving'), ('SERVED', 'Served to Table'), ('BILL_REQUESTED', 'Bill Requested'), ('BILL_GENERATED', 'Bill Generated'), ('PAID', 'Payment Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.tablesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('addons_json', models.JSONField(blank=True, default=list)),
                ('special_instructions', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Kitchen Acceptance'), ('PREPARING', 'In Preparation'), ('READY', 'Prepared & Ready'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('changed_by', models.CharField(default='System', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
