# Generated by Django 6.1.1 on 2026-09-06 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_waiter_called_table_waiter_called_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='is_bill_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_count', models.PositiveIntegerField(default=2)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.CharField(help_text='e.g. 19:30 or 07:30 PM', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special requests, e.g. celebration, window seat')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated / Arrived'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('is_alert_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tables.table')),
            ],
            options={
                'ordering': ['reservation_date', 'reservation_time', '-created_at'],
            },
        ),
    ]
