# Generated by Django 6.1.1 on 2026-09-07 18:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='General', help_text='e.g. Dairy, Coffee, Produce, Bakery, Packaging', max_length=50)),
                ('unit', models.CharField(choices=[('g', 'Grams (g)'), ('kg', 'Kilograms (kg)'), ('ml', 'Milliliters (ml)'), ('l', 'Liters (L)'), ('pcs', 'Pieces (pcs)'), ('portions', 'Portions')], default='g', max_length=15)),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_alert_level', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Triggers low stock alert', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cost per gram, ml, or piece', max_digits=8)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('RESTOCK', 'Restock / Purchase Inward'), ('ORDER_CONSUMED', 'Order Kitchen Consumption'), ('WASTAGE', 'Wastage / Spoilage'), ('MANUAL_CORRECTION', 'Manual Count Adjustment')], max_length=25)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for addition, negative for deduction', max_digits=10)),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='e.g. Order #1002 or Invoice PO-882', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('performed_by', models.CharField(default='Manager', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='menu.ingredient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Amount in ingredient's base unit (e.g. 18g, 220ml)", max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='menu.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='menu.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
