# Generated by Django 6.1.1 on 2026-09-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(default='coffee', help_text='icon name like coffee, pizza, cake, cup-soda', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=8)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Ingredient cost', max_digits=8)),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_veg', models.BooleanField(default=True)),
                ('spice_level', models.PositiveSmallIntegerField(choices=[(0, 'Not Spicy'), (1, 'Mild 🌶️'), (2, 'Medium 🌶️🌶️'), (3, 'Hot 🌶️🌶️🌶️')], default=0)),
                ('prep_time_mins', models.PositiveIntegerField(default=15)),
                ('is_available', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Extra Cheese, Hazelnut Syrup, Oat Milk', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, help_text='Blank if applies cafe-wide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Regular, Large, Double Shot', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem')),
            ],
        ),
    ]
