# Generated by Django 6.1.1 on 2026-09-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='System', max_length=100)),
                ('role', models.CharField(default='System', max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The Roasted Bean & Co.', max_length=150)),
                ('tagline', models.CharField(default='Artisan Coffee & Gourmet Bistro', max_length=255)),
                ('address', models.TextField(default='42 Heritage Boulevard, Downtown, Mumbai 400001')),
                ('phone', models.CharField(default='+91 98201 23456', max_length=20)),
                ('email', models.EmailField(default='contact@roastedbean.cafe', max_length=254)),
                ('gstin', models.CharField(default='27AABCU9603R1ZN', max_length=20)),
                ('currency', models.CharField(default='₹', max_length=10)),
                ('tax_rate_cgst', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('tax_rate_sgst', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('auto_accept_orders', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner / Admin'), ('MANAGER', 'Cafe Manager'), ('CASHIER', 'Cashier / Billing'), ('KITCHEN', 'Kitchen Staff')], default='CASHIER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
