# Generated by Django 6.1.1 on 2026-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cafeprofile_advance_booking_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeprofile',
            name='fssai_license',
            field=models.CharField(blank=True, default='11521018000452', help_text='FSSAI Food Safety License Number', max_length=30),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='receipt_footer',
            field=models.CharField(blank=True, default='Thank you for dining with us! Please visit again.', max_length=255),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='receipt_header',
            field=models.CharField(blank=True, default='Welcome to Musafirr Cafe & Bistro!', max_length=255),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='sender_mobile',
            field=models.CharField(default='+91 98201 55667', help_text='Designated mobile number from which WhatsApp/SMS receipts and alerts are sent', max_length=20),
        ),
    ]
